volumes:
  node_modules:
services:
  my-app-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
      - '24678:24678'
    command: [ "npm", "run", "dev"]
    volumes:
      - .:/src
      - node_modules:/src/node_modules