services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: handy-backend-service
        deploy:
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 6
        container_name: handy-backend-service-app
        ports:
            - "8061:80"
        env_file:
            - ./.env